--- # second conditinal playbook
- name: second condtion playbook
  hosts: webservers
  user: ansible
  become: yes
  connection: ssh


  tasks: 
    - name: install https package
      yum: 
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"


    - name: start httpd service
      service: 
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"


    - name: install apache2 package
      apt: 
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: start apache2 service
      service: 
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: copy index.html
      copy: 
        src: /home/ansible/index.html
        dest: /var/www/html

             

        
