--- 
- name: variables playbook
  hosts: all
  become: yes
  user: ansible
  connection: ssh


  vars_files: 
    - user.yml


  tasks: 
    - name: creating user {{user2}}
      user: 
        name: "{{user2}}"
